services:
  backend-spring:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-todolist
    environment:
      - DOCKER_HOST=10.42.2.126
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend-spring
